emdgroup-liquid/liquid

src/liquid/components/ld-toggle/ld-toggle.css, src/liquid/components/ld-toggle/ld-toggle.tsx, src/liquid/components/ld-toggle/readme.md, src/liquid/components/ld-toggle/test/__snapshots__/ld-toggle.spec.ts.snap, src/liquid/components/ld-toggle/test/ld-toggle.e2e.ts, src/liquid/components/ld-toggle/test/ld-toggle.spec.ts
=> refactor(toggle): rename mode prop to size

.gitignore, package.json, src/docs/pages/react-bindings.md, src/docs/pages/sandbox-applications.md, src/docs/pages/server-side-rendering.md, src/docs/pages/tailwindcss-integration.md, src/liquid/components/ld-toggle/ld-toggle.css, stencil.config.ts, tsconfig.react.json, yarn.lock
Adds React bindings in a separate build step.
=> feat: add react bindings

src/liquid/components/ld-select/ld-select.tsx, src/liquid/components/ld-select/test/__snapshots__/ld-select.spec.ts.snap, src/liquid/components/ld-select/test/ld-select.spec.ts
Fixes docs-pick-theme throwing exception on selection issue.
=> fix(ld-select): init ld-option-internal with up-to-date props

src/liquid/components/ld-label/ld-label.css, src/liquid/components/ld-label/test/ld-label.e2e.ts
Visual regression tests are currently failing as they include other components which have not been themed yet.
=> feat(ld-label): use up-to-date css custom props

.eleventy.js
This will hopefully fix build errors, such as this one: https://github.com/emdgroup-liquid/liquid/runs/4178505853?check_suite_focus=true
=> ci(contributors): account for empty or no contributors list

yarn.lock
=> chore(deps): upgrade all deps based on specified range

src/liquid/components/ld-select/ld-select.tsx, src/liquid/components/ld-select/test/ld-select.spec.ts
=> fix(ld-select): ld-select not opening up on mobile safari

src/liquid/components/ld-icon/readme.md, src/liquid/components/ld-input/ld-input.tsx, src/liquid/components/ld-input/readme.md, src/liquid/components/ld-input/test/__snapshots__/ld-input.spec.ts.snap, src/liquid/components/ld-input/test/ld-input.spec.ts, src/liquid/utils/__mocks__/cloneAttributes.ts, src/liquid/utils/cloneAttributes.ts
=> fix(ld-input): prop forwarding

src/liquid/components/ld-button/ld-button.tsx, src/liquid/components/ld-button/test/ld-button.e2e.ts, src/liquid/components/ld-button/test/ld-button.spec.ts
=> fix(ld-button): prop forwarding

src/liquid/components/ld-typo/readme.md, src/liquid/global/styles/colors/index.md, src/liquid/global/styles/typography/index.md
Adds references to the brand hub using the "warning message" style.
=> docs: add brand hub references

CONTRIBUTING.md, README.md, scripts/copyReadmeAndLicenseToPages.ts, src/index.md
=> docs(readme): add quick links to most relevant resources

src/liquid/components/ld-tabs/ld-tabs.tsx, src/liquid/components/ld-tabs/test/__snapshots__/ld-tabs.spec.ts.snap, src/liquid/components/ld-tabs/test/ld-tabs.spec.ts
=> fix(ld-tabs): show tabpanel according to preselected tab

src/docs/components/docs-nav/docs-nav.css, src/docs/components/docs-pick-theme/docs-pick-theme.tsx, src/docs/components/docs-search/docs-search.tsx, src/docs/components/docs-toc/docs-toc.css, src/docs/components/docs-topbar/docs-topbar.css, src/docs/components/docs-topbar/docs-topbar.tsx, src/docs/includes/layout.njk, src/docs/layouts/docs-layout/docs-layout.css, src/docs/pages/component-assets.md, src/docs/pages/getting-started.md, src/docs/pages/server-side-rendering.md
=> docs: fix minor layout issues and allow expanding nav sections, update docs around ssr and component import options

.eleventy.js, package.json, src/docs/pages/css-vs-web-components.md, src/liquid/components/ld-button/readme.md, src/liquid/components/ld-checkbox/readme.md, src/liquid/components/ld-input-message/readme.md, src/liquid/components/ld-input/readme.md, src/liquid/components/ld-notification/readme.md, src/liquid/components/ld-radio/readme.md, src/liquid/components/ld-sr-only/readme.md, src/liquid/components/ld-tabs/readme.md, src/liquid/components/ld-typo/readme.md, src/liquid/global/styles/theming/index.md, yarn.lock
=> docs(example): upgrade 11ty to v1 and refactor example short code

.eleventy.js, src/docs/components/docs-example/docs-example.css, src/docs/components/docs-example/docs-example.tsx, src/docs/components/docs-nav/docs-nav.tsx, src/liquid/components/ld-bg-cells/readme.md
=> docs(ld-bg-cells): remove paddings from examples

screenshot/builds/master.json, src/docs/components/docs-main/docs-main.css, src/liquid/components/ld-input/ld-input.css, src/liquid/components/ld-input/ld-input.tsx, src/liquid/components/ld-input/readme.md, src/liquid/components/ld-input/test/__snapshots__/ld-input.spec.ts.snap, src/liquid/components/ld-input/test/ld-input.e2e.ts
Resolves #223 by adding a resize prop to the ld-input element.
=> feat(ld-input): add resize prop

src/docs/pages/component-assets.md, stencil.config.ts
=> feat: recursively auto-define child components

src/liquid/components/ld-sidenav/ld-sidenav-navitem/ld-sidenav-navitem.tsx, src/liquid/components/ld-sidenav/test/__snapshots__/ld-sidenav.spec.ts.snap
Fixes tooltip not showing up on nav item with slotted icon.
=> fix(ld-sidenav): show tooltip with slotted icon

LICENSE.md, README.md, src/docs/components/docs-nav/docs-nav.tsx, src/docs/pages/data-visualization/getting-started.md, src/docs/pages/introduction/component-assets.md, src/docs/pages/license.md, src/docs/pages/terms.md, src/index.md
Make domain-relative URLs work properly with the new domains and replacing the old domain with the new one.
=> docs: update all links to work with new domain

tsconfig.react.json
Properly exports React bindings as CommonJS.
Fixes #429
=> fix: properly export react bindings

scripts/applyDesignTokens.ts, src/docs/pages/guides/design-tokens.md, src/docs/pages/introduction/getting-started.md, src/liquid/components/ld-progress/ld-progress.css, src/liquid/global/styles/tailwindPreset.ts
Updates the scripts for importing/generating the design tokens and tailwind preset to be more robust. Tiny changes to the docs.
Fixes #(issue)
=> fix: make design tokens import more robust

src/docs/pages/guides/troubleshooting/index.md, src/docs/pages/guides/troubleshooting/popped-out-element-is-rendered-in-wrong-container.md
Start of improving documentation by splitting up troubleshooting to easily append new troubleshootings on individual pages.
=> Docs: Troubleshooting restructuring

package.json, yarn.lock
This PR includes an upgrade of @stencil/core to version 3.2.1, which includes a fix that is required for testing liquid components with the react testing library (see https://github.com/ionic-team/stencil/issues/3434).
=> fix(upstream): incorporate stencil fixes in release

package.json, scripts/patchVueOutput.ts, yarn.lock
Fixes Vue output target patch.
=> fix(vue-output-target): patch range

scripts/iconsUpdate.ts, src/liquid/utils/assetPath.ts
This PR includes a fix for the CDN url that is used to download assets.
=> fix(ld-icon): cdn url must contain the latest version

.github/workflows/ci-cd.yml
This PR changes the Node.js version used in the CI pipeline to 20 and updates the checkout action to version 4.
=> ci: use node 20
