emdgroup-liquid/liquid

src/liquid/components/ld-button/test/ld-button.e2e.ts
src/liquid/components/ld-button/test/ld-button.spec.ts
src/liquid/components/ld-checkbox/test/ld-checkbox.e2e.ts
src/liquid/components/ld-checkbox/test/ld-checkbox.spec.ts
src/liquid/components/ld-icon/test/ld-icon.e2e.ts
src/liquid/components/ld-input/test/ld-input.e2e.ts
src/liquid/components/ld-input/test/ld-input.spec.ts
src/liquid/components/ld-radio/test/ld-radio.e2e.ts
src/liquid/components/ld-radio/test/ld-radio.spec.ts
src/liquid/components/ld-select/test/ld-select.e2e.ts
src/liquid/components/ld-select/test/ld-select.spec.ts
src/liquid/components/ld-sr-only/test/ld-sr-only.e2e.ts
src/liquid/components/ld-toggle/test/ld-toggle.e2e.ts
src/liquid/components/ld-toggle/test/ld-toggle.spec.ts
stencil.config.ts

Replace all timers with fake timers in unit tests. This results in more readable tests and faster execution.

test: use fake timers for unit tests

---

src/liquid/components/ld-input-message/ld-input-message.css

This looks good, as soon as the updated success theme color vars from #71 are merged.

refactor(ld-input-message): use new color vars

---

src/docs/pages/getting-started.md
stencil.config.ts

Adds the [dist-custom-elements](https://stenciljs.com/docs/custom-elements) output target to Liquid.
This has been tested locally in the SvelteKit Sandbox app via yarn link.

build(dist-custom-elements): build custom elements bundle

---

src/liquid/components/ld-icon/ld-icon.tsx
src/liquid/components/ld-tabs/ld-tab/ld-tab.css

This PR resolves a regression which has been introduced with 16605f068c9d7f87a929d0585d4b92df99661a9a
Safari seems to add style tags to the shadow DOM while other browsers (such as Opera and Chrome) do not do this. This fix makes sure no style tags are removed in the shadow DOM.
Fixes #124
Manual testing in Safari and Opera.

fix(ld-icon): make sure shadow dom style element is not removed

---

src/liquid/components/ld-button/ld-button.css

In Safari the button has a default margin of a few pixels. This PR includes a reset for the ld-button margin.

fix(ld-button): reset margin for safari

---

src/liquid/components/ld-input/ld-input.css

Makes the textarea inherit max/min-width/height values. This is necessary to give the developer the possibility to prevent horizontal and/or vertical resizing of the textarea.

fix(ld-input): let textarea inherit max/min sizes

---

.github/workflows/ci-cd.yml

(Hopefully) fixes the CI build that does yet exclude the `bin/` folder from the build artifacts.

ci: add bin folder to artifacts

---

src/liquid/components/ld-button/test/__snapshots__/ld-button.spec.ts.snap
src/liquid/components/ld-button/test/ld-button.spec.ts
src/liquid/utils/cloneAttributes.ts

Seems like the cloneAttributes utility can be simplified in a way that there is no need to determine attributes to clone to a element contained in the shadow dom via props. This fixes the linked issue. 
Fixes #190

fix(clone-attributes): determining attributes from props is unnecessary and causes issues

---

src/liquid/components/ld-button/ld-button.tsx
src/liquid/components/ld-checkbox/ld-checkbox.tsx
src/liquid/components/ld-input/ld-input.tsx
src/liquid/components/ld-label/ld-label.tsx
src/liquid/components/ld-radio/ld-radio.tsx
src/liquid/components/ld-toggle/ld-toggle.tsx
src/liquid/components/ld-typo/ld-typo.tsx

`this.attributeObserver` is sometimes undefined at the time that the `disconnectedCallback` is being called. This PR checks, if `this.attributeObserver˚ is defined, before calling its `disconnect` method.

fix: conditionally disconnect attribute observer

---

src/liquid/components/ld-input/ld-input.tsx
src/liquid/components/ld-input/test/ld-input.spec.ts

Adds functionality to automatically request submit on the associated form of an `ld-input` component.
Fixes #183

fix(ld-input): submit associated form on return

---

src/liquid/components/ld-button/ld-button.tsx

I don't know yet why this didn't pop up as an issue in the unit tests. The change doesn't really have an effect on the snapshots, however it fixes the anchor buttons in the docs where the href is missing. We might need to investigate further. 
**Test Configuration**:
Navigate to https://emdgroup-liquid.github.io/liquid/introduction/css-vs-web-components/ and click on the Back button at the bottom of the page. It will do nothing. Now start up the docs page from this branch and try the same. You will see that the link works.

fix(ld-button): non-reflected props are not cloned as attributes

---

globals.d.ts
src/docs/pages/component-assets.md
src/docs/pages/react-bindings.md
src/docs/pages/type-checking-and-intellisense.md
src/liquid/components/ld-bg-cells/ld-bg-cells.tsx
src/liquid/components/ld-icon/fetchIcon.ts
src/liquid/components/ld-icon/ld-icon.tsx
src/liquid/utils/e2e-tests.ts
src/liquid/utils/getLdAssetPath.ts
tsconfig.docs.json
tsconfig.json

Adds an alternate approach to setting the asset path when using React bindings. Updates the [documentation](https://emdgroup-liquid.github.io/liquid/introduction/component-assets/) accordingly.
Fixes #230

fix(react): add alternate approach for setting the asset path

---

src/liquid/components/ld-input/ld-input.css
src/liquid/components/ld-input/ld-input.tsx
src/liquid/components/ld-input/readme.md
src/liquid/components/ld-input/test/ld-input.e2e.ts
src/liquid/components/ld-label/ld-label.css
src/liquid/components/ld-select/ld-option-internal/ld-option-internal.css
src/liquid/components/ld-select/ld-option-internal/ld-option-internal.tsx
src/liquid/components/ld-select/ld-select.css
src/liquid/components/ld-select/ld-select.tsx
src/liquid/utils/cloneAttributes.ts

This PR includes changes to the cloneAttributes utility where we make sure that attributes containing a `"false"` value (type string) are considered false. It replaces usages of `[disabled]` in CSS with explicit modifier classes set in either via TSX or by the developer when working with CSS components.
Fixes #229
Fixes #235

fix: make disabled attributes work with false in react

---

.eleventy.js
package.json
src/docs/components/docs-main/docs-main.css
src/docs/components/docs-topbar/docs-topbar.css
src/docs/layouts/docs-layout/docs-layout.css
yarn.lock

This PR adds dependency information to the component documentation. For that to work it includes am 11ty config tweak which transforms relative links to absolute ones. Also this PR fixes minor layout issues in the docs.

docs(docs-main): show component dependencies

---

src/liquid/components/ld-input/ld-input.tsx
src/liquid/components/ld-input/test/ld-input.spec.ts

This PR fixes issue where the focus is forced to the date component of the date picker when clicking the year component on Safari.
**Test Configuration**:
- browsers: Safari, Opera

fix(ld-input): cannot focus year on safari

---

src/liquid/components/ld-tooltip/ld-tooltip-popper/ld-tooltip-popper.css
src/liquid/components/ld-tooltip/ld-tooltip-popper/ld-tooltip-popper.tsx
src/liquid/components/ld-tooltip/test/__snapshots__/ld-tooltip.spec.ts.snap

This PR replaces the pseudo element which was used for the tooltip arrow in lite DOM with a span element used within the shadow DOM. This fixes an issue where reset styles, specifically tailwind preflight styles, override border related styles on pseudo elements, which results in the arrow not showing at all.

fix(ld-tooltip): move arrow into shadow dom

---

src/liquid/components/ld-typo/ld-typo.css

This PR adds a reset to the ld-typo CSS component, making sure that margins on paragraphs with the `ld-typo` class are reset (with a specificity of zero), so that the CSS component behaves consistently with its WebComponent counterpart.

fix(ld-typo): add reset for css component

---

src/liquid/components/ld-tooltip/ld-tooltip.tsx

Fix a bug that prevented tooltip triggers from having their own onClick event listeners.

fix(ld-tooltip): remove stopPropagation for mouse events on triggerType hover

---

src/docs/pages/introduction/sandbox-applications.md

As code sandbox node environments do not fit to Astro Requirements I prepared the sandbox project to use StackBlitz.
This PR just adds a new sandbox to the docs.
Documentation

docs: Adds Astro Sandbox to docs

---

src/liquid/components/ld-modal/ld-modal.css
src/liquid/components/ld-modal/readme.md

This PR makes sure that focus outlines are displayed correctly when the close button of the modal dialog is focused.
It also includes some fixes to the examples in the documentation accounting for weird issues related to combining will-change on the examples container with fixed position of the dialog element.

fix(ld-modal): hide displaced focus outlines

---

src/liquid/components/ld-select/ld-select.tsx
src/liquid/components/ld-select/test/__snapshots__/ld-select.spec.ts.snap
src/liquid/components/ld-select/test/ld-select.spec.ts

This PR fixes the filtering feature of the ld-select component making sure that it filters using the options' text content instead of the options' value. This allows using misc. values on options without effecting the filtering capability of the component.
Fixes #393

fix(ld-select): filter by option text content instead of option value

---

src/docs/pages/guides/troubleshooting.md
src/liquid/components/ld-select/readme.md
src/liquid/components/ld-tooltip/readme.md

This PR adds more detailed instructions on how to handle *z-order* related issues when dealing with popping components such as the ld-select and the ld-tooltip components.
Resolves #411
The new example code has been tested manually on codesandbox.io in order to make sure that it works.

docs: improve troubleshooting docs related to popping components

---

src/liquid/components/ld-input/ld-input.tsx

Fixes #401
I tried writing unit and e2e tests for this without success. Hope the comment I left will give enough clue to future developers (including "future me") that the `|| undefined` part should not be removed.

fix(ld-input): make sure minus character is not ignored

---

src/liquid/components/ld-tabs/ld-tablist/ld-tablist.tsx

Safari seems to be calculating offset differently than "normal browsers". This PR includes a change which makes sure the offset is calculated correctly in all browsers based on the bounding client rect left property of the selected tab and its parent element.
Fixes #424

fix(ld-tabs): safari layout bug due to different offset calculation

---

src/liquid/components/ld-accordion/ld-accordion-section/ld-accordion-section.tsx
src/liquid/components/ld-select/ld-select.tsx

I noticed that the `ld-select` component doesn't expand on click in a Solid.js app. Turns out that in the Solid.js app the event target is the actual element clicked within the shadow DOM of the `ld-select` component, while in other apps (React, Vue, Svelte etc.) the event target is always the component host element itself. I don't know why the event target is a different one in a Solid.js app. The fix is simple enough however: I replaced all (2) occurrences of `ev.target.closest` with our `closest` util function which penetrates shadow DOM boundaries.

fix: event target closest is this element check

---

src/liquid/components/ld-sidenav/ld-sidenav.tsx
src/liquid/components/ld-sidenav/test/ld-sidenav.spec.ts

This PR fixes an issues where sub-components are not aware of dynamic changes to the `ld-sidenav`'s `collapsible` prop / state by changing the collapsed prop to false as soon as the component is not callapsible anymore, which in turn is picked up by a watcher which dispatches the `ldSidenavCollapsedChange` event.

fix(ld-sidenav): dispatch collapsed change event on collapsible change

---

src/liquid/components/ld-sidenav/ld-sidenav-header/ld-sidenav-header.tsx
src/liquid/components/ld-sidenav/ld-sidenav-toggle-outside/ld-sidenav-toggle-outside.tsx
src/liquid/components/ld-sidenav/ld-sidenav.tsx
src/liquid/components/ld-sidenav/test/__snapshots__/ld-sidenav.spec.ts.snap
src/liquid/components/ld-sidenav/test/ld-sidenav.spec.ts

This PR fixes an issue where the sidenav header toggle is not updated if the sidenav collapsible prop is changed.

fix(ld-sidenav): update toggle in sidenav header on collapsible change

---

src/liquid/components/ld-sidenav/ld-sidenav-accordion/ld-sidenav-accordion.shadow.css
src/liquid/components/ld-sidenav/ld-sidenav-accordion/ld-sidenav-accordion.tsx
src/liquid/components/ld-sidenav/ld-sidenav-header/ld-sidenav-header.tsx
src/liquid/components/ld-sidenav/ld-sidenav-navitem/ld-sidenav-navitem.shadow.css
src/liquid/components/ld-sidenav/ld-sidenav-navitem/ld-sidenav-navitem.tsx
src/liquid/components/ld-sidenav/ld-sidenav-separator/ld-sidenav-separator.shadow.css
src/liquid/components/ld-sidenav/ld-sidenav-separator/ld-sidenav-separator.tsx
src/liquid/components/ld-sidenav/ld-sidenav-toggle-outside/ld-sidenav-toggle-outside.tsx
src/liquid/components/ld-sidenav/ld-sidenav.shadow.css
src/liquid/components/ld-sidenav/test/__snapshots__/ld-sidenav.spec.ts.snap
src/liquid/components/ld-sidenav/utils/toggleStackToTop.ts

The `ldSidenavCollapsedChange` event can be fired before this components within the `ld-sidenav` component's slot are loaded. That is why the need to update there stacking to top (in narrow mode) after they have loaded. The issue is currently not reproducible in the liquid docs, however it is reproducible in the Solid.js sandbox app that is currently in development.

fix(ld-sidenav): update stacking to top on component did load

---

src/liquid/components/ld-accordion/ld-accordion-toggle/ld-accordion-toggle.tsx
src/liquid/components/ld-accordion/test/__snapshots__/ld-accordion.spec.tsx.snap
src/liquid/components/ld-accordion/test/ld-accordion.spec.tsx
src/liquid/components/ld-sidenav/test/__snapshots__/ld-sidenav.spec.ts.snap

Instead of setting the `aria-expanded` attribute to `undefined` we now set it to `false` when an element is collapsed. That way a screen reader will tell the user that the element is expandable.

fix(ld-accordion): indicate expandable state when collapsed

---

package.json
src/docs/components/docs-main/docs-main.css
src/docs/pages/guides/framework-integrations/index.md
src/docs/pages/guides/framework-integrations/react-bindings.md
src/docs/pages/guides/framework-integrations/vue-bindings.md
stencil.config.ts
tsconfig.vue.json
yarn.lock

This pull request adds a Vue output target to the project (similar to the one we already have for React). It improves the DX for Vue developers by enabling type checking and intellisense in Vue templates. This has been tested and proved to be working well in Visual Studio Code in combination with the Volar plugin.

feat(vue): add vue output target

---

src/liquid/components/ld-stepper/ld-step/ld-step.css

This PR removes a line of code that seems to have no useful effect, but results in the `::after` pseudo element, that draws a line from one step to the next, being covered by a container which wraps the `ld-stepper` component and has no explicit z-order:

fix(ld-stepper): z-index issue when in placed container without explicit z-order

---

.github/workflows/ci-cd.yml

Adds a step to the deployment action that invalidates the cloudfront cache.
Also added the required secrets to the repository settings.

ci: invalidate cloudfront cache

---

src/liquid/components/ld-button/ld-button.tsx
src/liquid/components/ld-button/test/ld-button.spec.ts

Stopping propagation of click events is important for clicks on child elements within the ld-button, because otherwise event handlers attached to the ld-button are still executed (no matter if the event was prevented or not).
The bug is reproducible in the current docs by clicking on the text of a disabled button.

fix(ld-button): stop propagation of click event if disabled

---

src/liquid/components/ld-switch/ld-switch-item/ld-switch-item.css
src/liquid/components/ld-switch/ld-switch.css

This is reproducible in the docs. It's hardly visible, but the switch in the code examples has a smaller height than the button. This change fixes that.

fix(ld-switch): switch has wrong height

---

.eleventy.cjs
src/docs/components/docs-example/docs-example.css
src/docs/components/docs-example/docs-example.tsx
src/docs/components/docs-nav/docs-nav.css
src/liquid/components/ld-accordion/readme.md
src/liquid/components/ld-button/readme.md

This PR changes how we document components, by adding the ability to add code examples for React. This is the [option 6 from #459](https://github.com/emdgroup-liquid/liquid/issues/459#issuecomment-1385278038).

docs(react): examples in code viewer

---

src/liquid/components/ld-accordion/ld-accordion-panel/ld-accordion-panel.tsx
src/liquid/components/ld-accordion/ld-accordion-panel/readme.md
src/liquid/components/ld-accordion/ld-accordion.tsx
src/liquid/components/ld-accordion/readme.md
src/liquid/components/ld-select/ld-option-internal/ld-option-internal.tsx
src/liquid/components/ld-select/ld-select-popper/ld-select-popper.tsx
src/liquid/components/ld-stepper/ld-stepper.tsx
src/liquid/components/ld-stepper/readme.md
src/liquid/components/ld-table/ld-table.tsx
src/liquid/components/ld-table/readme.md
src/liquid/components/ld-tabs/ld-tab/ld-tab.tsx
src/liquid/components/ld-tabs/ld-tab/readme.md
src/liquid/components/ld-tabs/ld-tabs.tsx

<details>
<summary>This is a change fixing typing issues with adding inline event listeners in TSX to components, which are receiving those events from their sub-components. (click to expand for details)
</summary>
<br>
Assume you have component that emits a custom event, for instance the ld-accordion-section component.
Now assume you have a parent component that listens to this event, for instance the ld-accordion component.
Assume you now attach attach an event listener to the parent component in a TSX context:
```tsx
<LdAccordion onLdaccordionchange={(ev) => { /* ... */}}>{/* ... */}</LdAccordion>
```
As a result you receive a warning from the Typescript compiler:
> Property 'onLdaccordionchange' does not exist on type 'IntrinsicAttributes & Pick<StencilReactExternalProps<LdAccordion, …

fix(types): copy bubbling events type definitions to parent

---

src/liquid/components/ld-pagination/readme.md
src/liquid/components/ld-progress/ld-progress.css
src/liquid/components/ld-progress/readme.md
src/liquid/components/ld-radio/readme.md
src/liquid/components/ld-select/readme.md
src/liquid/components/ld-sr-live/readme.md
src/liquid/components/ld-sr-only/readme.md

Adds React examples for the following components:
- ld-select
- ld-sr-only
- ld-sr-live
- ld-radio
- ld-progress
- ld-pagination
Fixes a CSS issue for `ld-progress`.

docs: add more react examples

---

src/liquid/components/ld-icon/readme.md
src/liquid/components/ld-input-message/readme.md
src/liquid/components/ld-input/readme.md
src/liquid/components/ld-label/readme.md
src/liquid/components/ld-link/readme.md
src/liquid/components/ld-loading/readme.md
src/liquid/components/ld-modal/readme.md
src/liquid/components/ld-notice/readme.md
src/liquid/components/ld-notification/readme.md

Adds React examples for the following components:
- ld-icon
- ld-input
- ld-input-message
- ld-label
- ld-link
- ld-loading
- ld-modal
- ld-notice
- ld-notification
Fixes a CSS issue for `ld-progress`.

docs: add even more react examples

---

src/liquid/components/ld-slider/readme.md

Adds react examples to the `ld-slider` documentation.
Depends on #485 ⚠️

docs(ld-slider): add react examples

---

src/liquid/components/ld-input/ld-input.css
src/liquid/components/ld-input/ld-input.tsx
src/liquid/components/ld-input/readme.md
src/liquid/components/ld-input/test/ld-input.spec.ts

This PR fixes ld-input with type file not dispatching events in Safari. It also fixes an issue with the file dialog opening twice due to internal dispatching of click events. It also fixes a layout issue in Safari by adding a margin reset to the input element.
Fixes #497

fix(ld-input): type file not dispatching in safari

---

.gitignore
.yarn/patches/@stencil-react-output-target-npm-0.3.1-4da13663f2.patch
.yarn/patches/@stencil-vue-output-target-npm-0.6.2-a9b3828cb9.patch
package.json
yarn.lock

This PR includes a patch to the Stencil Vue and React output targets, resolving an issue with relatively imported modules, which need to have the .js or /index.js extension to be added to the import path in order to resolve an actual path, when working with esm in environments, where a fully specified path is the default (such as in a create react app with webpack 5, which, if not ejected and changed, has [resolve.fullySpecified](https://webpack.js.org/configuration/module/#resolvefullyspecified) set to true).
Fixes #495
References:
- Issue https://github.com/ionic-team/stencil-ds-output-targets/issues/319
- PR https://github.com/ionic-team/stencil-ds-output-targets/pull/322
In order to test this, you'll need to do the following:
1. Inside the liquid project working directory, check out …

fix: add patch to fully specify resolve path in stencil output targets

---

src/liquid/components/ld-input/ld-input.tsx
src/liquid/components/ld-input/readme.md
src/liquid/components/ld-input/test/__snapshots__/ld-input.spec.ts.snap
src/liquid/components/ld-input/test/ld-input.spec.ts

This pull request adds two event emitters to the `ld-input` component, emitted when the component has the `type` prop set to `'file'`. The detail property of the custom events contains the file data, which is necessary to read the files on client side via the FileReader API, or to create a FormData object and send it to a server.

feat(ld-input): add ldinputfile and ldchangefile events

---

.yarn/patches/@stencil-react-output-target-npm-0.3.1-4da13663f2.patch
.yarn/patches/@stencil-vue-output-target-npm-0.6.2-a9b3828cb9.patch
stencil.config.ts

Sets the output target for vue and react to use `includeDefineCustomElements: true`.
This PR is also updating the patch as the import did not use index.js.
```
import { defineCustomElements } from '../dist/loader/index.js';
defineCustomElements();
```
This will influence the documentation which is still pending.
The output target was tested in respective react sandboxes. 
Due to the missing patch there was an issue with vitest and jest.

feat: autoDefineCustomComponents for React and Vue

---

src/liquid/utils/assetPath.ts

This PR uses jsDelivr as default asset base path. 
It will improve the DX when Liquid gets introduced into a project. As this is not the recommended approach for production 
additional documentation will be provided. 
It's marked as feature as it improves the DX but does not actually fix anything.
Docuementation will be updated with [PR 506](https://github.com/emdgroup-liquid/liquid/pull/506).
- [-] I have made corresponding changes to the documentation

feat: introduces default asset path to jsDelivr

---

src/liquid/components/ld-accordion/ld-accordion-toggle/ld-accordion-toggle.tsx
src/liquid/components/ld-bg-cells/ld-bg-cells.tsx
src/liquid/components/ld-button/ld-button.tsx
src/liquid/components/ld-checkbox/ld-checkbox.tsx
src/liquid/components/ld-icon/ld-icon.tsx
src/liquid/components/ld-input/ld-input.tsx
src/liquid/components/ld-link/ld-link.tsx
src/liquid/components/ld-radio/ld-radio.tsx
src/liquid/components/ld-select/ld-option-internal/ld-option-internal.tsx
src/liquid/components/ld-select/ld-option/ld-option.tsx
src/liquid/components/ld-select/ld-select-popper/ld-select-popper.tsx
src/liquid/components/ld-select/ld-select.tsx
src/liquid/components/ld-sidenav/ld-sidenav-navitem/ld-sidenav-navitem.tsx
src/liquid/components/ld-sidenav/ld-sidenav-slider/ld-sidenav-slider.tsx
src/liquid/components/ld-sidenav/ld-sidenav-slider/readme.md
src/liquid/components/ld-sidenav/ld-sidenav-subnav/ld-sidenav-subnav.tsx
src/liquid/components/ld-sidenav/ld-sidenav-subnav/readme.md
src/liquid/components/ld-sidenav/ld-sidenav-toggle-outside/ld-sidenav-toggle-outside.tsx
src/liquid/components/ld-slider/ld-slider.tsx
src/liquid/components/ld-stepper/ld-step/ld-step.tsx
src/liquid/components/ld-switch/ld-switch-item/ld-switch-item.tsx
src/liquid/components/ld-switch/ld-switch.tsx
src/liquid/components/ld-table/ld-table-cell/ld-table-cell.tsx
src/liquid/components/ld-table/ld-table-col/ld-table-col.tsx
src/liquid/components/ld-table/ld-table-colgroup/ld-table-colgroup.tsx
src/liquid/components/ld-tabs/ld-tab/ld-tab.tsx
src/liquid/components/ld-toggle/ld-toggle.tsx
src/liquid/components/ld-tooltip/ld-tooltip.tsx
src/liquid/components/ld-typo/ld-typo.tsx
src/types/index.d.ts

This PR is related to https://github.com/emdgroup-liquid/liquid/pull/522#issue-1591976674 and fixes more component prop types which do not have a default value and are marked as required, although they are not. This has effects in some environments such as in Plotly Dash, where we see error messages, such as:
> TypeError: Required argument `value` was not specified.
This PR fixes the issue, changing the type definition of each prop with a default value by marking it as _optional_ with `?`.

fix(types): mark props which are undefined by default as optional

---

.gitignore
config/tsconfig.react.json
config/tsconfig.vue.json
package.json
scripts/patchReactOutput.ts
scripts/patchVueOutput.ts
src/liquid/components/ld-slider/ld-slider.tsx
src/liquid/components/ld-slider/readme.md
stencil.config.ts
yarn.lock

Due to the recent version bump of several packages including the react and vue output target plugins our custom patches were not applied anymore. This is fixed. 
Additionally the vue output target got the definition config to enable vue `v-model`. 
Unfortunately the output target is still refering to lazy loaded components as the non-lazy-loaded bundle is not tree-shakable. 
See: https://github.com/ionic-team/stencil-ds-output-targets/issues/255
Updated Documentation will follow with the Documentation PR.

fix: Fixes patches and improves react and vue output target.

---

src/liquid/components/ld-circular-progress/ld-circular-progress.css

This PR fixes a layout issue in the circular progress component which occurs on Safari.
Fixes #544

fix(ld-circular-progress): safari requires width to be set to 100% on svg

---

src/liquid/components/ld-circular-progress/ld-circular-progress.css
stencil.config.ts

This PR fixes a layout issue in the circular progress component which occurs on Safari due to the usage of a negative stroke dash offset. The stroke dash offset is now normalized to a positive value so that it works on all browsers.
Fixes #544

fix(ld-circular-progress): negative stroke dash offset issue on safari

---

src/liquid/components/ld-circular-progress/ld-circular-progress.css

This PR includes a fix for normal browsers and a special hack for Safari which resolves issues with the precision of the circular progress display.
Related to #544

fix(ld-circular-progress): precision

---

src/liquid/components/ld-input/readme.md

This PR adds a short explainer on the date format topic to the `ld-input` docs.
Resolves #553

docs(ld-input): add date format explainer

---

src/liquid/components/ld-sr-live/ld-sr-live.shadow.css

This PR includes a fix to the `ld-sr-live` component making sure its host element, which is  the `ld-sr-live` element itself, doesn't become part of the page layout, by adding a `display: contents;` style to it. Its direct child element is an `ld-sr-only` component and hence does not participate in the page layout either.

fix(ld-sr-live): remove host element from layout

---

src/liquid/components/ld-switch/ld-switch.css

fix(ld-switch): use display inline-flex on host element

---

src/liquid/components/ld-label/ld-label.tsx
src/liquid/components/ld-label/test/ld-label.spec.ts

This PR includes a fix which makes sure that an `ld-label` component, which does not have any child element, doesn't throw an error, when clicked.
Fixes #578

fix(ld-label): throws on click when without child

---

src/liquid/components/ld-badge/test/__snapshots__/ld-badge.spec.tsx.snap
src/liquid/components/ld-icon/ld-icon.tsx
src/liquid/components/ld-icon/test/__snapshots__/ld-icon.spec.tsx.snap
src/liquid/components/ld-stepper/ld-step/test/__snapshots__/ld-step.spec.tsx.snap
src/liquid/components/ld-tooltip/ld-tooltip.tsx

Fixes the missing icons in the tooltips of the collapsed `ld-sidenav` component.

fix(ld-sidenav): icon not showing in tooltips

---

package.json
src/liquid/components/ld-notification/ld-notification.tsx
src/liquid/components/ld-notification/readme.md
src/liquid/components/ld-notification/test/__mocks__/dompurify.ts
src/liquid/components/ld-notification/test/ld-notification.spec.ts
yarn.lock

This PR resolves a security vulnerability which results from HTML content being rendered by the `ld-notification` component without prior sanitization. The issue is resolved by sanitizing the HTML string internally. Sanitization config options are provided.
Fixes #625

fix(ld-notification): sanitize html content passed to notification

---

src/liquid/components/ld-notification/ld-notification.tsx
src/liquid/components/ld-notification/readme.md
src/liquid/components/ld-notification/test/ld-notification.spec.ts

This PR changes how timeouts can be set on the `ld-notification` component, by adding the ability to set an explicit timeout on notifications with type `"alert"`. Notifications with type `"alert"` still do not timeout by default, making sure that important messages stay accessible with the initial configuration. However, we add the possibility to set a timeout for use cases where alert messages are very frequent, but do not carry important information.
Resolves #629

feat(ld-notification): allow setting timeout on type alert notifications

---

src/liquid/components/ld-table/ld-table.tsx
src/liquid/components/ld-table/test/ld-table.spec.tsx

This PR fixes a null pointer exception thrown on selectable tables without table-head by adding a guard.
Fixes #635

fix(ld-table): selectable table without table head throws exception

---

src/liquid/components/ld-select/ld-select.tsx
src/liquid/components/ld-select/test/ld-select.spec.ts

This PR adds a feature to the `ld-select` component, enabling it to render HTML content from selected options in the select trigger button. Previously the component only rendered the text content of the options. This feature allows for more customization of the select component.
Resolves #633

feat(ld-select): render option html content in trigger button

---

src/liquid/components/ld-icon/ld-icon.tsx
src/liquid/components/ld-icon/test/__snapshots__/ld-icon.spec.tsx.snap
src/liquid/components/ld-icon/test/ld-icon.spec.tsx

This PR includes a guard which makes sure that the `ld-icon` component does not throw an exception, when hydrated in a unit test.

fix(ld-icon): icon component throws when hydrated in tests

---

scripts/patchLoader.ts
scripts/patchReactOutput.ts
scripts/patchVueOutput.ts

The ES5 polyfill included in the default loader messes with prettyDOM, which is used by testing-library. To fix this, we patch the loader package.json, the react and the vue output target imports to use the ES2017 code.
Fixes #699

fix(loader): use ES2017 loader

---

src/liquid/components/ld-card/ld-card.tsx
src/liquid/components/ld-card/test/ld-card.spec.tsx

This PR includes a small fix which makes sure that the `ld-card` component doesn't throw an exception if there is no parent element available. This can happen if the `componentWillLoad` lifecycle hook is executed after removal of the Node from the DOM.

fix(ld-card): throws if there is no parent element

---

src/docs/pages/guides/troubleshooting/failed-to-execute-removeChild-on-node.md
src/docs/pages/guides/troubleshooting/index.md

This PR addresses an issue where UI libraries such as React try to remove conditionally rendered elements from the DOM by executing `removeChild` on the parent `Node`, but fail to do so, because components with a popper element, such as the `ld-tooltip`, move the element to a portal element (aka the popper element), which results in the following error message:
> Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
The issue is addressed by adding a troubleshooting section which suggests to simply wrap the conditionally rendered element in another element.
Resolves #744

docs(troubleshooting): failed to execute removeChild on Node

---

src/liquid/components/ld-context-menu/test/ld-context-menu.spec.tsx
src/liquid/components/ld-tooltip/ld-tooltip.tsx

This PR fixes an issue with the ld-context-menu component where it always opens on right-click no matter if right-click is enabled or not.

fix(ld-context-menu): do not open on right click if not enabled

---

src/liquid/components/ld-tabs/ld-tablist/ld-tablist.tsx
src/liquid/components/ld-tabs/ld-tabs.tsx
src/liquid/components/ld-tabs/test/ld-tabs.spec.ts

We want the tablist to scroll in a way that the selected tab is presented in the horizontal middle of the scroll area. We initially chose to use the scrollIntoView() method with the inline: 'center' option for this. However, this results in scrolling of elements wrapping the ld-tabs component as well. This change addresses the issue by replacing the usage of scrollIntoView() with the usage of the scrollTo() method.
Fixes #792

fix(ld-tabs): replace scrollIntoView with scrollTo

---

src/liquid/components/ld-badge/test/ld-badge.spec.tsx
src/liquid/components/ld-breadcrumbs/test/ld-breadcrumbs.spec.tsx
src/liquid/components/ld-context-menu/ld-menuitem/test/ld-menuitem.spec.tsx
src/liquid/components/ld-input/test/ld-input.spec.ts
src/liquid/components/ld-select/ld-select.tsx
src/liquid/components/ld-select/test/ld-select.spec.ts
src/liquid/components/ld-tabs/ld-tablist/test/ld-tablist.spec.ts
src/liquid/components/ld-tooltip/test/ld-tooltip.spec.ts
src/liquid/utils/mutationObserver.ts

It looks like the Tether enable method returns before the actual popper element is visible. So we need to "wait" for it to become visible before setting the focus on the filter input element.
Fixes #813

fix(ld-select): wait for popper to be visible before focusing filter

---

src/liquid/components/ld-sidenav/ld-sidenav-slider/ld-sidenav-slider.tsx
src/liquid/components/ld-sidenav/ld-sidenav-slider/readme.md
src/liquid/components/ld-sidenav/test/ld-sidenav.spec.ts

This PR adds an event to the `ld-sidenav` component, which is emitted after navigation (after the transition ends).

feat(ld-sidenav): emit event after navigation (after transition ends)

---

.gitignore
config/.eslintrc.cjs
package.json
src/docs/pages/guides/server-side-rendering.md
src/docs/pages/guides/type-checking-and-intellisense.md
stencil.config.ts

This PR adds the [hydrate-app output target](https://stenciljs.com/docs/hydrate-app) to the stencil config. It allows to render web components on server side and hydrate them on client side.
I have experimented with this using Nuxt and Next, but didn't come too far, because of different hydration errors, mostly related to mismatches between client and server rendered HTML. I haven't had the time to report this to the Stencil team yet. However, I decided to push my changes and create a draft PR so that we don't loose this topic out of sight.

feat(ssr): add dist-hydrate-script output target

---

src/liquid/components/ld-input/ld-input.css

This PR fixes an issue where disabled input fields have a slightly lighter text color on Safari than they should.

fix(ld-input): disabled color on safari

---

src/liquid/components/ld-sidenav/ld-sidenav-header/ld-sidenav-header.tsx
src/liquid/components/ld-sidenav/test/__snapshots__/ld-sidenav.spec.ts.snap

This PR add missing shadow parts to the ld-sidenav-header component.

fix(ld-sidenav): add shadow parts to sidenav header

---

src/liquid/utils/closest.ts
src/liquid/utils/test/closest.spec.tsx

We encountered an issue with the `ld-sidenav` component throwing an error when listening for a `'focusout'` event on `window`. The `relatedTarget` of the event was `document`. The sidenav checked if the focus was inside the sidenav by calling the `closest` utility function. The `closest` utility function tried to execute the `closest` method on the `document` which was passed in as an argument, which lead to an exception being thrown.
This PR addresses the issue by fixing the `closest` utility function in a way that it returns `undefined` when passed an element that does not have a `closest` method (i.e. the `document`).

fix(closest): account for closest method being undefined on document

---

scripts/applyDesignTokens.ts
src/docs/components/docs-example/docs-example.tsx
src/liquid/components/ld-select/ld-select.tsx
src/liquid/components/ld-select/test/ld-select.spec.ts
src/liquid/components/ld-sidenav/ld-sidenav.tsx
src/liquid/components/ld-slider/ld-slider.tsx
src/liquid/components/ld-switch/ld-switch.tsx

This PR fixes an issue where the ld-select component use the selected option's inner HTML as title, thus rendering an HTML string.
Fixes #1033

fix(ld-select): use selected option value text as title

---

.github/dependabot.yml
package.json
pnpm-lock.yaml
src/liquid/components/ld-tabs/ld-tablist/ld-tablist.tsx
src/liquid/components/ld-tabs/ld-tablist/readme.md

Emit event on tablist scrollable change. This feature is relevant, if you want to react to the scroll buttons appearing as soon as the tablist cannot fit all tabs and becomes scrollable or vice versa.

feat(ld-tabs): emit event on tablist scrollable change

---

src/liquid/components/ld-breadcrumbs/ld-crumb/ld-crumb.css

The styles of the last breadcrumb item is now switched with the style of the other breadcrumb items, to have a more persistent style for links across components.

feat(ld-crumb): switch last/non-last crumb link styles
